---
- name: Run Container
  become: yes
  hosts: all
  vars_files:
    - extra_vars/config.yml
    - virtual_machine_vars/deployment.yml
    - virtual_machine_vars/partitions.yml
    - virtual_machine_vars/virtual_machines.yml
  roles:
    - role_2046
