---

- name: Some operation
  hosts: login
  tasks:
    - name: Import user
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} user_import.sh

    - name: Connect the container to macvlan network
      command: podman network connect macvlan-"{{ network_outer_parent }}" {{ hostvars[inventory_hostname].containers[0] }}
      become: yes
    - name: Flush the IP address on eth1 of the container
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} ip addr flush dev eth1
      become: yes
    - name: Add IP address to eth1 of the container
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} ip addr add {{ outer_ip[0] }} dev eth1
      become: yes
    - name: Set eth1 interface up
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} ip link set eth1 up
      become: yes
    - name: Add default route on eth1 interface
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} ip route add default via {{ network_outer_gateway }} dev eth1 proto static metric 200
      become: yes


- name: Some operation
  hosts: control
  tasks:
    - name: Flush db cache
      command: podman exec -it {{ hostvars[inventory_hostname].containers[0] }} systemctl restart slurmdbd