- name: Create dir
  shell: |
    mkdir -p "{{ config_file_path }} {{ state_file_volume }} {{ login_auth_file_volume }} {{ mysql_data_volume }}"
    chmod 776 "{{ config_file_path }} {{ state_file_volume }} {{ login_auth_file_volume }} {{ mysql_data_volume }}"

- name: slurm.conf
  template:
    src: slurm.conf.j2
    dest: "{{ config_file_path }}/slurm.conf"
    lstrip_blocks: true
    mode: "0644"
  become: no

- name: gres.conf
  template:
    src: gres.conf.j2
    dest: "{{ config_file_path }}/gres.conf"
    mode: "0600"
    lstrip_blocks: true

- name: minion
  template:
    src: minion.j2
    dest: "{{ config_file_path }}/minion"
    lstrip_blocks: true

- name: slurmdbd.conf
  template:
    src: slurmdbd.conf.j2
    dest: "{{ config_file_path }}/slurmdbd.conf"
    mode: "0600"
    lstrip_blocks: true

- name: slurmd_override.conf
  template:
    src: slurmd_override.conf.j2
    dest: "{{ config_file_path }}/slurmd_override.conf"
    lstrip_blocks: true
