- name: create dir
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ config_file_path }}"
    - "{{ state_file_volume }}"
    - "{{ ldap_file_volume }}"
    - "{{ mysql_data_volume }}"

- name: create slurm.conf
  template:
    src: slurm.conf.j2
    dest: "{{ config_file_path }}/slurm.conf"
    lstrip_blocks: true
    mode: "0644"

- name: create gres.conf
  template:
    src: gres.conf.j2
    dest: "{{ config_file_path }}/gres.conf"
    mode: "0600"
    lstrip_blocks: true

- name: create slurmdbd.conf
  template:
    src: slurmdbd.conf.j2
    dest: "{{ config_file_path }}/slurmdbd.conf"
    mode: "0600"
    lstrip_blocks: true

- name: create slurmd_override.conf
  template:
    src: slurmd_override.conf.j2
    dest: "{{ config_file_path }}/slurmd_override.conf"
    lstrip_blocks: true
