---
- name: === Set Vars Task Begin ===
  include_tasks: set_vars.yaml
  when: task_set_vars_enabled | default(true) | bool

- name: === Generate Templates Task Begin ===
  include_tasks: generate_templates.yaml
  when: task_generate_templates_enabled | default(true) | bool

- name: === Pull Image Task Begin ===
  include_tasks: pull_image.yaml
  when: task_pull_image_enabled | default(true) | bool

- name: === Before Running Task Begin ===
  include_tasks: before_running.yaml
  when: task_before_running_enabled | default(true) | bool

- name: === Runtime Task Begin ===
  include_tasks: runtime.yaml
  when: task_runtime_enabled | default(true) | bool

- name: === After Running Task Begin ===
  include_tasks: after_running.yaml
  when: task_after_running_enabled | default(true) | bool
