---

- name: Import config file on compute
  shell: |
    podman cp {{ config_file_path }}/minion {{ item.name }}:/etc/salt/minion
    podman cp {{ config_file_path }}/slurmd_override.conf {{ item.name }}:/etc/systemd/system/slurmd.service.d/override.conf
  when: item.type == "compute"
  loop: "{{ containers }}"

- name: Import config file on control
  shell: |
    podman cp {{ config_file_path }}/slurm.conf {{ item.name }}:/etc/slurm/slurm.conf
    podman cp {{ config_file_path }}/gres.conf {{ item.name }}:/etc/slurm/gres.conf
    podman cp {{ config_file_path }}/slurmdbd.conf {{ item.name }}:/etc/slurm/slurmdbd.conf
    podman cp {{ config_file_path }}/minion {{ item.name }}:/etc/salt/minion
  when: item.type == "control"
  loop: "{{ containers }}"

- name: Import config file on login
  shell: |
    podman cp {{ config_file_path }}/slurmd_override.conf {{ item.name }}:/etc/systemd/system/slurmd.service.d/override.conf
  when: item.type == "login"
  loop: "{{ containers }}"

- name: Import user
  shell: podman exec {{ item.name }} user_import.sh
  when: item.import_user | default(false)
  loop: "{{ containers }}"

- name: Add network
  shell: |
    podman network connect {{ item.outer_network }} {{ item.name }}
    podman exec {{ item.name }} ip addr flush dev eth1
    podman exec {{ item.name }} ip addr add {{ item.outer_ip }}/16 dev eth1
    podman exec {{ item.name }} ip link set eth1 up
    podman exec {{ item.name }} ip route add default via {{ item.outer_gateway }} dev eth1 proto static metric 50
  when: item.type == "login"
  loop: "{{ containers }}"

- name: Flush control & db
  shell: |
    podman exec {{ item.name }} chown slurm /etc/slurm/slurmdbd.conf
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmdbd
    podman exec {{ item.name }} systemctl restart slurmctld
    sleep 10
  when: item.type == "control"
  loop: "{{ containers }}"

- name: Flush login
  shell: |
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmd
  when: item.type == "login"
  loop: "{{ containers }}"

- name: Flush compute
  shell: |
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmd
    podman exec {{ item.name }} systemctl restart salt-minion
  when: item.type == "compute"
  loop: "{{ containers }}"