---

- name: Pull image
  containers.podman.podman_image:
    name: "{{ containers[item.type].image }}"
    state: present
    force: yes
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"


- name: Clean up unused podman images
  command: "podman image prune -f"


