---

- name: Hostname to ip
  set_fact:
    hosts_list: "{{ hosts_list | default({}) | combine({item.name: item.ip}) }}"
  loop: "{{ all_containers }}"
  when: item.name is defined and item.ip is defined


- name: Run container
  containers.podman.podman_container:
    name: "{{ item.name }}"
    hostname: "{{ item.name }}"
    image: "{{ containers[item.type].image }}"
    state: "started"
    recreate: true
    network: "{{ hostvars[item.parent].network[0].name }}"
    ip: "{{ item.ip }}"
    etc_hosts: "{{ hosts_list }}"
    privileged: true
    restart_policy: "on-failure"
    systemd: "true"
    volumes: >
      [
        {% if containers[item.type].nas %}
          "nas_volume:{{ container_nas_path }}",
        {% endif %}
        {% if item.type in ['control'] %}
          "{{ state_file_volume }}:/var/spool/slurmctld",
        {% endif %}
        {% if item.type in ['mysql'] %}
          "{{ mysql_data_volume }}:/var/lib/mysql",
        {% endif %}
        {% if item.type in ['login'] %}
          "{{ login_auth_file_volume }}:/auth_files",
        {% endif %}
      ]
    env:
      MYSQL_ROOT_PASSWORD: "{{ containers.mysql.password }}"
    device: "{{ 'nvidia.com/gpu=all' if containers[item.type].gpu | default(false) else omit }}"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true
