---

- name: Hostname to ip
  set_fact:
    hosts_list: "{{ hosts_list | default({}) | combine({item.name: item.ip}) }}"
  loop: "{{ all_containers }}"
  when: item.name is defined and item.ip is defined


- name: Run container
  containers.podman.podman_container:
    name: "{{ item.name }}"
    hostname: "{{ item.name }}"
    image: "{{ images[item.type] }}"
    state: "started"
    recreate: true
    network: "{{ hostvars[item.parent].network[0].name }}"
    ip: "{{ item.ip }}"
    etc_hosts: "{{ hosts_list }}"
    privileged: true
    restart_policy: "on-failure"
    systemd: "true"
    volumes: >
      [
        {% if containers[item.type].nas %}
          "nas_volume:/ifs",
        {% endif %}
        {% if item.type in ['mysql'] %}
          "{{ mysql_data_volume }}",
        {% endif %}
        {% if item.type in ['login'] %}
          "{{ login_auth_file_volume }}",
        {% endif %}
      ]
    env:
      MYSQL_ROOT_PASSWORD: "{{ containers.mysql.password }}"
    device: "{{ item.type == 'compute' and containers[item.type].gpu or omit }}"
  
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true
