---

- name: Import compute config file
  shell: |
    podman cp {{ config_file_path }}/minion {{ item.name }}:/etc/salt/minion
    podman cp {{ config_file_path }}/slurmd_override.conf {{ item.name }}:/etc/systemd/system/slurmd.service.d/override.conf
  when: item.type == "compute"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Import control config file
  shell: |
    podman cp {{ config_file_path }}/slurm.conf {{ item.name }}:/etc/slurm/slurm.conf
    podman cp {{ config_file_path }}/gres.conf {{ item.name }}:/etc/slurm/gres.conf
    podman cp {{ config_file_path }}/slurmdbd.conf {{ item.name }}:/etc/slurm/slurmdbd.conf
    podman cp {{ config_file_path }}/minion {{ item.name }}:/etc/salt/minion
    podman exec {{ item.name }} chown slurm /etc/slurm/slurmdbd.conf
    podman exec {{ item.name }} chmod 644 /etc/slurm/gres.conf
    podman exec {{ item.name }} chown slurm:slurm /etc/slurm/gres.conf
    podman exec {{ item.name }} chown -R slurm:slurm /var/spool/slurmctld
    podman exec {{ item.name }} chmod -R 750 /var/spool/slurmctld
  when: item.type == "control"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Import login config file
  shell: |
    podman cp {{ config_file_path }}/slurmd_override.conf {{ item.name }}:/etc/systemd/system/slurmd.service.d/override.conf
  when: item.type == "login"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Import user
  shell: podman exec {{ item.name }} user_import.sh
  when: item.type == "login"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Add network
  shell: |
    podman network connect {{ hostvars[item.parent].network[1].name }} {{ item.name }}
    podman exec {{ item.name }} ip addr flush dev eth1
    podman exec {{ item.name }} ip addr add {{ item.public_ip }} dev eth1
    podman exec {{ item.name }} ip link set eth1 up
    podman exec {{ item.name }} ip route add default via {{ hostvars[item.parent].network[1].gateway }} dev eth1 proto static metric 50
  when: item.type == "login"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Flush control
  shell: |
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmctld
    podman exec {{ item.name }} systemctl restart slurmdbd
  when: item.type == "control"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Flush login
  shell: |
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmd
  when: item.type == "login"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Flush compute
  shell: |
    podman exec {{ item.name }} systemctl daemon-reload
    podman exec {{ item.name }} systemctl restart slurmd
    podman exec {{ item.name }} systemctl restart salt-minion
  when: item.type == "compute"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true


- name: Reload state file
  shell: |
    sleep 100
    podman exec {{ item.name }} scontrol reconfigure
  when: item.type == "control"
  delegate_to: "{{ item.parent }}"
  loop: "{{ all_containers }}"
  run_once: true
